### ISSUE TITLE
entries order not sorted

### ISSUE THREAD

**Issue by huangziwei** [kodedninja/orkl#5]
https://github.com/kodedninja/orkl/blob/7b3f225c687c417c599a9ada6dd9d674805c3057/src/orkl.js#L85

Once I have more than 10 entries, the entries order starts misbehaving. I don't know anything about javascript, but I modified the sort function to be a little bit more explicit, and it works fine again. So I guess there's a bug there? 

          state.orkl.content.sort((a, b) => {

            if (b.date == a.date) {
          
              if (b.ctime - a.ctime) {
                return 1
              } else{
                return -1
              }     
              } else {
                if (b.date > a.date) {
                  return 1
                } else {
                  return -1
                }
            }
          })

**Comment by kodedninja** [comment]
Thanks for the bug report! The problem was with ```return b.date > a.date```, because it returned 0 and not minus something when the date was smaller. The corrent form is ```return b.date - a.date```.

I ended up not using your code, because it's simpler and shorter to write it this way.
